#!/usr/bin/env php
<?php

declare(strict_types = 1);

use MoritaBox\Server;

define('BASE_DIR', dirname(__FILE__));

# Composer initialization
if ( file_exists( BASE_DIR . '/vendor/autoload.php' ) ) {
    include BASE_DIR . '/vendor/autoload.php';
}

(function() {
    $server = new Server('127.0.0.1:8025');
})();